stages:
  - run

build:
  image: frolvlad/alpine-bash
  stage: run
  tags:
    - k8s
  script:
    - echo "Script run"
#  Ниже нужно исправить имя вашего файла
    - bash test.sh
    - echo "Script done"